version: '3.9'

services:
  api:
    container_name: smart_health_api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
      - /home/api/node_modules/bcrypt/
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: nest_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
