version: '3.9'

services:
  api:
    container_name: smart_health_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      API_PORT: ${API_PORT}
  database:
    image: postgres:13
    container_name: nest_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: smart_health
    ports:
      - '5432:5432'
